# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\OneDrive\PythonFile\RV_software\RV_1203\main_window.ui',
# licensing of 'F:\OneDrive\PythonFile\RV_software\RV_1203\main_window.ui' applies.
#
# Created: Tue Dec  4 14:11:09 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1239, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/rv_design.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1031, 601))
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main_design = QtWidgets.QWidget()
        self.tab_main_design.setObjectName("tab_main_design")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_main_design)
        self.groupBox_13.setGeometry(QtCore.QRect(30, 40, 291, 301))
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.groupBox_13)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(30, 20, 221, 121))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.spinBox_gearteeth_min = QtWidgets.QSpinBox(self.gridLayoutWidget_14)
        self.spinBox_gearteeth_min.setObjectName("spinBox_gearteeth_min")
        self.gridLayout_14.addWidget(self.spinBox_gearteeth_min, 1, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_92.setObjectName("label_92")
        self.gridLayout_14.addWidget(self.label_92, 3, 0, 1, 1)
        self.doubleDoubleSpinBox_main_speed_ratio = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_14)
        self.doubleDoubleSpinBox_main_speed_ratio.setMaximum(999.0)
        self.doubleDoubleSpinBox_main_speed_ratio.setObjectName("doubleDoubleSpinBox_main_speed_ratio")
        self.gridLayout_14.addWidget(self.doubleDoubleSpinBox_main_speed_ratio, 3, 1, 1, 1)
        self.doubleSpinBox_first_speed_ratio = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_14)
        self.doubleSpinBox_first_speed_ratio.setMaximum(999.0)
        self.doubleSpinBox_first_speed_ratio.setObjectName("doubleSpinBox_first_speed_ratio")
        self.gridLayout_14.addWidget(self.doubleSpinBox_first_speed_ratio, 2, 1, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_99.setObjectName("label_99")
        self.gridLayout_14.addWidget(self.label_99, 2, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_72.setObjectName("label_72")
        self.gridLayout_14.addWidget(self.label_72, 1, 0, 1, 1)
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.groupBox_13)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(30, 160, 221, 113))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.spinBox_main_zp = QtWidgets.QSpinBox(self.gridLayoutWidget_15)
        self.spinBox_main_zp.setEnabled(True)
        self.spinBox_main_zp.setObjectName("spinBox_main_zp")
        self.gridLayout_15.addWidget(self.spinBox_main_zp, 0, 1, 1, 1)
        self.doubleSpinBox_main_rp = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_15)
        self.doubleSpinBox_main_rp.setMaximum(999.0)
        self.doubleSpinBox_main_rp.setObjectName("doubleSpinBox_main_rp")
        self.gridLayout_15.addWidget(self.doubleSpinBox_main_rp, 2, 1, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_94.setObjectName("label_94")
        self.gridLayout_15.addWidget(self.label_94, 2, 0, 1, 1)
        self.label_main_a0 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_main_a0.setObjectName("label_main_a0")
        self.gridLayout_15.addWidget(self.label_main_a0, 3, 1, 1, 1)
        self.pushButton_main_a0_calc = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_main_a0_calc.setObjectName("pushButton_main_a0_calc")
        self.gridLayout_15.addWidget(self.pushButton_main_a0_calc, 3, 0, 1, 1)
        self.pushButton_main_zp_calc = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_main_zp_calc.setObjectName("pushButton_main_zp_calc")
        self.gridLayout_15.addWidget(self.pushButton_main_zp_calc, 0, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_main_design)
        self.groupBox_14.setGeometry(QtCore.QRect(340, 40, 571, 521))
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayoutWidget_16 = QtWidgets.QWidget(self.groupBox_14)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(30, 40, 441, 31))
        self.gridLayoutWidget_16.setObjectName("gridLayoutWidget_16")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_101 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_101.setObjectName("label_101")
        self.gridLayout_16.addWidget(self.label_101, 0, 2, 1, 1)
        self.spinBox_main_planetary_wheel = QtWidgets.QSpinBox(self.gridLayoutWidget_16)
        self.spinBox_main_planetary_wheel.setMinimum(2)
        self.spinBox_main_planetary_wheel.setMaximum(3)
        self.spinBox_main_planetary_wheel.setObjectName("spinBox_main_planetary_wheel")
        self.gridLayout_16.addWidget(self.spinBox_main_planetary_wheel, 0, 1, 1, 1)
        self.comboBox_speed_ratio_deviation = QtWidgets.QComboBox(self.gridLayoutWidget_16)
        self.comboBox_speed_ratio_deviation.setObjectName("comboBox_speed_ratio_deviation")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_speed_ratio_deviation, 0, 3, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_97.setObjectName("label_97")
        self.gridLayout_16.addWidget(self.label_97, 0, 0, 1, 1)
        self.radioButton_actual_center_distance = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_actual_center_distance.setGeometry(QtCore.QRect(30, 120, 89, 16))
        self.radioButton_actual_center_distance.setObjectName("radioButton_actual_center_distance")
        self.radioButton_normal_module = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_normal_module.setGeometry(QtCore.QRect(180, 120, 89, 16))
        self.radioButton_normal_module.setObjectName("radioButton_normal_module")
        self.doubleSpinBox_d_or_mn = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_d_or_mn.setGeometry(QtCore.QRect(340, 120, 141, 22))
        self.doubleSpinBox_d_or_mn.setMaximum(999.0)
        self.doubleSpinBox_d_or_mn.setObjectName("doubleSpinBox_d_or_mn")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_14)
        self.tableWidget.setGeometry(QtCore.QRect(20, 200, 511, 281))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pushButton_main_calculate = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_main_calculate.setGeometry(QtCore.QRect(220, 160, 121, 31))
        self.pushButton_main_calculate.setObjectName("pushButton_main_calculate")
        self.label_102 = QtWidgets.QLabel(self.groupBox_14)
        self.label_102.setGeometry(QtCore.QRect(190, 490, 241, 16))
        self.label_102.setObjectName("label_102")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_main_design)
        self.groupBox_15.setGeometry(QtCore.QRect(30, 360, 291, 201))
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_15)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(40, 30, 211, 111))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_89 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_89.setObjectName("label_89")
        self.gridLayout_17.addWidget(self.label_89, 0, 0, 1, 1)
        self.spinBox_main_z1 = QtWidgets.QSpinBox(self.gridLayoutWidget_17)
        self.spinBox_main_z1.setObjectName("spinBox_main_z1")
        self.gridLayout_17.addWidget(self.spinBox_main_z1, 0, 1, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_93.setObjectName("label_93")
        self.gridLayout_17.addWidget(self.label_93, 2, 0, 1, 1)
        self.spinBox_main_z2 = QtWidgets.QSpinBox(self.gridLayoutWidget_17)
        self.spinBox_main_z2.setObjectName("spinBox_main_z2")
        self.gridLayout_17.addWidget(self.spinBox_main_z2, 1, 1, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_90.setObjectName("label_90")
        self.gridLayout_17.addWidget(self.label_90, 1, 0, 1, 1)
        self.doubleSpinBox_main_real_speed_ratio = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_17)
        self.doubleSpinBox_main_real_speed_ratio.setEnabled(False)
        self.doubleSpinBox_main_real_speed_ratio.setObjectName("doubleSpinBox_main_real_speed_ratio")
        self.gridLayout_17.addWidget(self.doubleSpinBox_main_real_speed_ratio, 2, 1, 1, 1)
        self.pushButton_main_speed_ratio_calc = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_main_speed_ratio_calc.setGeometry(QtCore.QRect(110, 160, 75, 23))
        self.pushButton_main_speed_ratio_calc.setObjectName("pushButton_main_speed_ratio_calc")
        self.tabWidget.addTab(self.tab_main_design, icon, "")
        self.tab_first_advanced = QtWidgets.QWidget()
        self.tab_first_advanced.setObjectName("tab_first_advanced")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_first_advanced)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 361, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 90, 261, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_first_ha = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_first_ha.setObjectName("doubleSpinBox_first_ha")
        self.gridLayout.addWidget(self.doubleSpinBox_first_ha, 1, 1, 1, 2)
        self.doubleSpinBox_first_b = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_first_b.setObjectName("doubleSpinBox_first_b")
        self.gridLayout.addWidget(self.doubleSpinBox_first_b, 4, 1, 1, 2)
        self.doubleSpinBox_first_alpha_n = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_first_alpha_n.setObjectName("doubleSpinBox_first_alpha_n")
        self.gridLayout.addWidget(self.doubleSpinBox_first_alpha_n, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.doubleSpinBox_first_mn = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_first_mn.setObjectName("doubleSpinBox_first_mn")
        self.gridLayout.addWidget(self.doubleSpinBox_first_mn, 0, 1, 1, 2)
        self.doubleSpinBox_first_hf = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_first_hf.setObjectName("doubleSpinBox_first_hf")
        self.gridLayout.addWidget(self.doubleSpinBox_first_hf, 2, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(120, 20, 54, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(200, 20, 54, 12))
        self.label_10.setObjectName("label_10")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 40, 241, 51))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spinBox_first_z1 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.spinBox_first_z1.setMaximum(999)
        self.spinBox_first_z1.setObjectName("spinBox_first_z1")
        self.gridLayout_5.addWidget(self.spinBox_first_z1, 0, 1, 1, 1)
        self.doubleSpinBox_first_b1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.doubleSpinBox_first_b1.setObjectName("doubleSpinBox_first_b1")
        self.gridLayout_5.addWidget(self.doubleSpinBox_first_b1, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.doubleSpinBox_first_b2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.doubleSpinBox_first_b2.setObjectName("doubleSpinBox_first_b2")
        self.gridLayout_5.addWidget(self.doubleSpinBox_first_b2, 1, 2, 1, 1)
        self.spinBox_first_z2 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.spinBox_first_z2.setMaximum(999)
        self.spinBox_first_z2.setObjectName("spinBox_first_z2")
        self.gridLayout_5.addWidget(self.spinBox_first_z2, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.pushButton_teethmatch_tool = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_teethmatch_tool.setGeometry(QtCore.QRect(270, 40, 78, 23))
        self.pushButton_teethmatch_tool.setObjectName("pushButton_teethmatch_tool")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_first_advanced)
        self.groupBox_4.setGeometry(QtCore.QRect(400, 10, 331, 261))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 271, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_first_inv_alpha = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_first_inv_alpha.setEnabled(False)
        self.lineEdit_first_inv_alpha.setReadOnly(False)
        self.lineEdit_first_inv_alpha.setObjectName("lineEdit_first_inv_alpha")
        self.gridLayout_2.addWidget(self.lineEdit_first_inv_alpha, 1, 1, 1, 1)
        self.doubleSpinBox_first_a = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_first_a.setEnabled(False)
        self.doubleSpinBox_first_a.setMaximum(999.99)
        self.doubleSpinBox_first_a.setObjectName("doubleSpinBox_first_a")
        self.gridLayout_2.addWidget(self.doubleSpinBox_first_a, 0, 1, 1, 1)
        self.lineEdit_x_sigma = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_x_sigma.setEnabled(False)
        self.lineEdit_x_sigma.setObjectName("lineEdit_x_sigma")
        self.gridLayout_2.addWidget(self.lineEdit_x_sigma, 2, 1, 1, 1)
        self.doubleSpinBox_first_x2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_first_x2.setMinimum(-99.0)
        self.doubleSpinBox_first_x2.setObjectName("doubleSpinBox_first_x2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_first_x2, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.doubleSpinBox_first_x1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_first_x1.setMinimum(-99.0)
        self.doubleSpinBox_first_x1.setObjectName("doubleSpinBox_first_x1")
        self.gridLayout_2.addWidget(self.doubleSpinBox_first_x1, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.pushButton_first_calculate = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_first_calculate.setGeometry(QtCore.QRect(120, 230, 75, 23))
        self.pushButton_first_calculate.setObjectName("pushButton_first_calculate")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_first_advanced)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 320, 381, 241))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 361, 126))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.lineEdit_eta_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_eta_2.setEnabled(False)
        self.lineEdit_eta_2.setObjectName("lineEdit_eta_2")
        self.gridLayout_3.addWidget(self.lineEdit_eta_2, 2, 2, 1, 1)
        self.lineEdit_eta_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_eta_1.setEnabled(False)
        self.lineEdit_eta_1.setObjectName("lineEdit_eta_1")
        self.gridLayout_3.addWidget(self.lineEdit_eta_1, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_alpha_a_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_alpha_a_2.setEnabled(False)
        self.lineEdit_alpha_a_2.setObjectName("lineEdit_alpha_a_2")
        self.gridLayout_3.addWidget(self.lineEdit_alpha_a_2, 0, 2, 1, 1)
        self.lineEdit_alpha_a_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_alpha_a_1.setEnabled(False)
        self.lineEdit_alpha_a_1.setObjectName("lineEdit_alpha_a_1")
        self.gridLayout_3.addWidget(self.lineEdit_alpha_a_1, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 3, 0, 1, 1)
        self.lineEdit_d_a1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_d_a1.setEnabled(False)
        self.lineEdit_d_a1.setObjectName("lineEdit_d_a1")
        self.gridLayout_3.addWidget(self.lineEdit_d_a1, 3, 1, 1, 1)
        self.lineEdit_d_f1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_d_f1.setEnabled(False)
        self.lineEdit_d_f1.setObjectName("lineEdit_d_f1")
        self.gridLayout_3.addWidget(self.lineEdit_d_f1, 4, 1, 1, 1)
        self.lineEdit_d_a2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_d_a2.setEnabled(False)
        self.lineEdit_d_a2.setObjectName("lineEdit_d_a2")
        self.gridLayout_3.addWidget(self.lineEdit_d_a2, 3, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 4, 0, 1, 1)
        self.lineEdit_d_f2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_d_f2.setEnabled(False)
        self.lineEdit_d_f2.setObjectName("lineEdit_d_f2")
        self.gridLayout_3.addWidget(self.lineEdit_d_f2, 4, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label_23.setObjectName("label_23")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(130, 50, 54, 12))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(260, 50, 54, 12))
        self.label_29.setObjectName("label_29")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 201, 361, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.lineEdit_epsilon_alpha = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_epsilon_alpha.setEnabled(False)
        self.lineEdit_epsilon_alpha.setObjectName("lineEdit_epsilon_alpha")
        self.horizontalLayout_3.addWidget(self.lineEdit_epsilon_alpha)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.lineEdit_epsilon_beta = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_epsilon_beta.setEnabled(False)
        self.lineEdit_epsilon_beta.setObjectName("lineEdit_epsilon_beta")
        self.horizontalLayout_3.addWidget(self.lineEdit_epsilon_beta)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_first_advanced)
        self.groupBox_6.setGeometry(QtCore.QRect(420, 290, 401, 271))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_20.setObjectName("label_20")
        self.comboBox_accuracy_level = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_accuracy_level.setGeometry(QtCore.QRect(110, 10, 241, 22))
        self.comboBox_accuracy_level.setObjectName("comboBox_accuracy_level")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.comboBox_accuracy_level.addItem("")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 381, 191))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_fpt_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_fpt_1.setMaximum(999.99)
        self.doubleSpinBox_fpt_1.setObjectName("doubleSpinBox_fpt_1")
        self.gridLayout_4.addWidget(self.doubleSpinBox_fpt_1, 3, 1, 1, 1)
        self.doubleSpinBox_Fp_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_Fp_1.setMaximum(999.99)
        self.doubleSpinBox_Fp_1.setObjectName("doubleSpinBox_Fp_1")
        self.gridLayout_4.addWidget(self.doubleSpinBox_Fp_1, 4, 1, 1, 1)
        self.doubleSpinBox_Fp_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_Fp_2.setMaximum(999.99)
        self.doubleSpinBox_Fp_2.setObjectName("doubleSpinBox_Fp_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_Fp_2, 4, 2, 1, 1)
        self.doubleSpinBox_F_beta2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_F_beta2.setMaximum(999.99)
        self.doubleSpinBox_F_beta2.setObjectName("doubleSpinBox_F_beta2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_F_beta2, 2, 2, 1, 1)
        self.doubleSpinBox_F_w2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_F_w2.setMaximum(999.99)
        self.doubleSpinBox_F_w2.setObjectName("doubleSpinBox_F_w2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_F_w2, 0, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 5, 0, 1, 1)
        self.doubleSpinBox_F_w1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_F_w1.setMaximum(999.99)
        self.doubleSpinBox_F_w1.setObjectName("doubleSpinBox_F_w1")
        self.gridLayout_4.addWidget(self.doubleSpinBox_F_w1, 0, 1, 1, 1)
        self.doubleSpinBox_fpt_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_fpt_2.setMaximum(999.99)
        self.doubleSpinBox_fpt_2.setObjectName("doubleSpinBox_fpt_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_fpt_2, 3, 2, 1, 1)
        self.doubleSpinBox_F_r1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_F_r1.setMaximum(999.99)
        self.doubleSpinBox_F_r1.setObjectName("doubleSpinBox_F_r1")
        self.gridLayout_4.addWidget(self.doubleSpinBox_F_r1, 6, 1, 1, 1)
        self.doubleSpinBox_F_beta1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_F_beta1.setMaximum(999.99)
        self.doubleSpinBox_F_beta1.setObjectName("doubleSpinBox_F_beta1")
        self.gridLayout_4.addWidget(self.doubleSpinBox_F_beta1, 2, 1, 1, 1)
        self.doubleSpinBox_ff_alpha_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_ff_alpha_1.setMaximum(999.99)
        self.doubleSpinBox_ff_alpha_1.setObjectName("doubleSpinBox_ff_alpha_1")
        self.gridLayout_4.addWidget(self.doubleSpinBox_ff_alpha_1, 5, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 2, 0, 1, 1)
        self.doubleSpinBox_F_r2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_F_r2.setMaximum(999.99)
        self.doubleSpinBox_F_r2.setObjectName("doubleSpinBox_F_r2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_F_r2, 6, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 6, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 3, 0, 1, 1)
        self.doubleSpinBox_ff_alpha_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_ff_alpha_2.setMaximum(999.99)
        self.doubleSpinBox_ff_alpha_2.setObjectName("doubleSpinBox_ff_alpha_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_ff_alpha_2, 5, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 7, 0, 1, 1)
        self.lineEdit_F_i1 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_F_i1.setObjectName("lineEdit_F_i1")
        self.gridLayout_4.addWidget(self.lineEdit_F_i1, 7, 1, 1, 1)
        self.lineEdit_F_i2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_F_i2.setObjectName("lineEdit_F_i2")
        self.gridLayout_4.addWidget(self.lineEdit_F_i2, 7, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setGeometry(QtCore.QRect(180, 50, 54, 12))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        self.label_34.setGeometry(QtCore.QRect(300, 50, 54, 12))
        self.label_34.setObjectName("label_34")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/advancetaskmanager.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_first_advanced, icon1, "")
        self.tab_first_check = QtWidgets.QWidget()
        self.tab_first_check.setObjectName("tab_first_check")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_first_check)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 20, 751, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(70, 39, 241, 171))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 2, 0, 1, 1)
        self.doubleSpinBox_first_rpm = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.doubleSpinBox_first_rpm.setObjectName("doubleSpinBox_first_rpm")
        self.gridLayout_7.addWidget(self.doubleSpinBox_first_rpm, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.doubleSpinBox_first_torsion = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.doubleSpinBox_first_torsion.setObjectName("doubleSpinBox_first_torsion")
        self.gridLayout_7.addWidget(self.doubleSpinBox_first_torsion, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 3, 0, 1, 1)
        self.doubleSpinBox_first_ka = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_7)
        self.doubleSpinBox_first_ka.setObjectName("doubleSpinBox_first_ka")
        self.gridLayout_7.addWidget(self.doubleSpinBox_first_ka, 3, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 0, 0, 1, 1)
        self.spinBox_planetary_wheel = QtWidgets.QSpinBox(self.gridLayoutWidget_7)
        self.spinBox_planetary_wheel.setMinimum(2)
        self.spinBox_planetary_wheel.setMaximum(3)
        self.spinBox_planetary_wheel.setObjectName("spinBox_planetary_wheel")
        self.gridLayout_7.addWidget(self.spinBox_planetary_wheel, 0, 1, 1, 1)
        self.pushButton_first_ka = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_first_ka.setGeometry(QtCore.QRect(320, 170, 21, 23))
        self.pushButton_first_ka.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/exclamation_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first_ka.setIcon(icon2)
        self.pushButton_first_ka.setObjectName("pushButton_first_ka")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(380, 10, 301, 276))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 0, 1, 1, 1)
        self.doubleSpinBox_s_hmin1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_s_hmin1.setObjectName("doubleSpinBox_s_hmin1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_s_hmin1, 3, 1, 1, 1)
        self.doubleSpinBox_e1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_e1.setObjectName("doubleSpinBox_e1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_e1, 5, 1, 1, 1)
        self.doubleSpinBox_nu1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_nu1.setObjectName("doubleSpinBox_nu1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_nu1, 6, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_56.setObjectName("label_56")
        self.gridLayout_8.addWidget(self.label_56, 5, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 1, 0, 1, 1)
        self.doubleSpinBox_delta_flim1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_delta_flim1.setObjectName("doubleSpinBox_delta_flim1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_delta_flim1, 2, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 2, 0, 1, 1)
        self.doubleSpinBox_nu2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_nu2.setObjectName("doubleSpinBox_nu2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_nu2, 6, 2, 1, 1)
        self.doubleSpinBox_hb2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_hb2.setObjectName("doubleSpinBox_hb2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_hb2, 7, 2, 1, 1)
        self.doubleSpinBox_z_nt1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_z_nt1.setDecimals(1)
        self.doubleSpinBox_z_nt1.setMinimum(1.0)
        self.doubleSpinBox_z_nt1.setMaximum(3.0)
        self.doubleSpinBox_z_nt1.setObjectName("doubleSpinBox_z_nt1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_z_nt1, 8, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_57.setObjectName("label_57")
        self.gridLayout_8.addWidget(self.label_57, 6, 0, 1, 1)
        self.doubleSpinBox_z_nt2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_z_nt2.setDecimals(1)
        self.doubleSpinBox_z_nt2.setMinimum(1.0)
        self.doubleSpinBox_z_nt2.setMaximum(3.0)
        self.doubleSpinBox_z_nt2.setObjectName("doubleSpinBox_z_nt2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_z_nt2, 8, 2, 1, 1)
        self.doubleSpinBox_s_hmin2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_s_hmin2.setObjectName("doubleSpinBox_s_hmin2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_s_hmin2, 3, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_60.setObjectName("label_60")
        self.gridLayout_8.addWidget(self.label_60, 8, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_59.setObjectName("label_59")
        self.gridLayout_8.addWidget(self.label_59, 7, 0, 1, 1)
        self.doubleSpinBox_delta_hlim2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_delta_hlim2.setObjectName("doubleSpinBox_delta_hlim2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_delta_hlim2, 1, 2, 1, 1)
        self.doubleSpinBox_doubleSpinBox_delta_flim2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_doubleSpinBox_delta_flim2.setObjectName("doubleSpinBox_doubleSpinBox_delta_flim2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_doubleSpinBox_delta_flim2, 2, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 0, 2, 1, 1)
        self.doubleSpinBox_hb1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_hb1.setObjectName("doubleSpinBox_hb1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_hb1, 7, 1, 1, 1)
        self.doubleSpinBox_e2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_e2.setObjectName("doubleSpinBox_e2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_e2, 5, 2, 1, 1)
        self.doubleSpinBox_delta_hlim1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_delta_hlim1.setObjectName("doubleSpinBox_delta_hlim1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_delta_hlim1, 1, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_58.setObjectName("label_58")
        self.gridLayout_8.addWidget(self.label_58, 3, 0, 1, 1)
        self.doubleSpinBox_s_fmin1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_s_fmin1.setObjectName("doubleSpinBox_s_fmin1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_s_fmin1, 4, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_62.setObjectName("label_62")
        self.gridLayout_8.addWidget(self.label_62, 4, 0, 1, 1)
        self.doubleSpinBox_s_fmin2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_s_fmin2.setObjectName("doubleSpinBox_s_fmin2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_s_fmin2, 4, 2, 1, 1)
        self.doubleSpinBox__y_nt2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox__y_nt2.setDecimals(1)
        self.doubleSpinBox__y_nt2.setMinimum(1.0)
        self.doubleSpinBox__y_nt2.setMaximum(3.0)
        self.doubleSpinBox__y_nt2.setObjectName("doubleSpinBox__y_nt2")
        self.gridLayout_8.addWidget(self.doubleSpinBox__y_nt2, 9, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_63.setObjectName("label_63")
        self.gridLayout_8.addWidget(self.label_63, 9, 0, 1, 1)
        self.doubleSpinBox_y_nt1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_y_nt1.setDecimals(1)
        self.doubleSpinBox_y_nt1.setMinimum(1.0)
        self.doubleSpinBox_y_nt1.setMaximum(3.0)
        self.doubleSpinBox_y_nt1.setObjectName("doubleSpinBox_y_nt1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_y_nt1, 9, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_64.setObjectName("label_64")
        self.gridLayout_8.addWidget(self.label_64, 10, 0, 1, 1)
        self.doubleSpinBox_rho_pie1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_rho_pie1.setMaximum(1.0)
        self.doubleSpinBox_rho_pie1.setObjectName("doubleSpinBox_rho_pie1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_rho_pie1, 10, 1, 1, 1)
        self.doubleSpinBox_rho_pie2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_8)
        self.doubleSpinBox_rho_pie2.setMaximum(1.0)
        self.doubleSpinBox_rho_pie2.setObjectName("doubleSpinBox_rho_pie2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_rho_pie2, 10, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 120, 21, 23))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_first_check)
        self.groupBox_7.setGeometry(QtCore.QRect(360, 330, 441, 231))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_7)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 20, 401, 201))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_sf_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_sf_1.setEnabled(False)
        self.lineEdit_sf_1.setObjectName("lineEdit_sf_1")
        self.gridLayout_6.addWidget(self.lineEdit_sf_1, 6, 1, 1, 1)
        self.lineEdit_sf_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_sf_2.setEnabled(False)
        self.lineEdit_sf_2.setObjectName("lineEdit_sf_2")
        self.gridLayout_6.addWidget(self.lineEdit_sf_2, 6, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 1, 0, 1, 1)
        self.lineEdit_sh_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_sh_2.setEnabled(False)
        self.lineEdit_sh_2.setObjectName("lineEdit_sh_2")
        self.gridLayout_6.addWidget(self.lineEdit_sh_2, 3, 2, 1, 1)
        self.lineEdit_delta_hp1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_hp1.setEnabled(False)
        self.lineEdit_delta_hp1.setObjectName("lineEdit_delta_hp1")
        self.gridLayout_6.addWidget(self.lineEdit_delta_hp1, 2, 1, 1, 1)
        self.lineEdit_sh_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_sh_1.setEnabled(False)
        self.lineEdit_sh_1.setObjectName("lineEdit_sh_1")
        self.gridLayout_6.addWidget(self.lineEdit_sh_1, 3, 1, 1, 1)
        self.lineEdit_delta_h1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_h1.setEnabled(False)
        self.lineEdit_delta_h1.setObjectName("lineEdit_delta_h1")
        self.gridLayout_6.addWidget(self.lineEdit_delta_h1, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 6, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 3, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 5, 0, 1, 1)
        self.lineEdit_delta_f2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_f2.setEnabled(False)
        self.lineEdit_delta_f2.setObjectName("lineEdit_delta_f2")
        self.gridLayout_6.addWidget(self.lineEdit_delta_f2, 4, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 2, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 4, 0, 1, 1)
        self.lineEdit_delta_f1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_f1.setEnabled(False)
        self.lineEdit_delta_f1.setObjectName("lineEdit_delta_f1")
        self.gridLayout_6.addWidget(self.lineEdit_delta_f1, 4, 1, 1, 1)
        self.lineEdit_delta_fp1 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_fp1.setEnabled(False)
        self.lineEdit_delta_fp1.setObjectName("lineEdit_delta_fp1")
        self.gridLayout_6.addWidget(self.lineEdit_delta_fp1, 5, 1, 1, 1)
        self.lineEdit_delta_fp2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_fp2.setEnabled(False)
        self.lineEdit_delta_fp2.setObjectName("lineEdit_delta_fp2")
        self.gridLayout_6.addWidget(self.lineEdit_delta_fp2, 5, 2, 1, 1)
        self.lineEdit_delta_h2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_h2.setEnabled(False)
        self.lineEdit_delta_h2.setObjectName("lineEdit_delta_h2")
        self.gridLayout_6.addWidget(self.lineEdit_delta_h2, 1, 2, 1, 1)
        self.lineEdit_delta_hp2 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_delta_hp2.setEnabled(False)
        self.lineEdit_delta_hp2.setObjectName("lineEdit_delta_hp2")
        self.gridLayout_6.addWidget(self.lineEdit_delta_hp2, 2, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 0, 2, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_first_check)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 340, 331, 221))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_8)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(30, 20, 261, 152))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_50.setObjectName("label_50")
        self.gridLayout_9.addWidget(self.label_50, 5, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_52.setObjectName("label_52")
        self.gridLayout_9.addWidget(self.label_52, 4, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_54.setObjectName("label_54")
        self.gridLayout_9.addWidget(self.label_54, 1, 0, 1, 1)
        self.spinBox_first_v40 = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.spinBox_first_v40.setObjectName("spinBox_first_v40")
        self.gridLayout_9.addWidget(self.spinBox_first_v40, 5, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_53.setObjectName("label_53")
        self.gridLayout_9.addWidget(self.label_53, 2, 0, 1, 1)
        self.doubleSpinBox_first_k = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        self.doubleSpinBox_first_k.setObjectName("doubleSpinBox_first_k")
        self.gridLayout_9.addWidget(self.doubleSpinBox_first_k, 1, 1, 1, 1)
        self.doubleSpinBox_first_l = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        self.doubleSpinBox_first_l.setObjectName("doubleSpinBox_first_l")
        self.gridLayout_9.addWidget(self.doubleSpinBox_first_l, 2, 1, 1, 1)
        self.doubleSpinBox_first_s = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        self.doubleSpinBox_first_s.setObjectName("doubleSpinBox_first_s")
        self.gridLayout_9.addWidget(self.doubleSpinBox_first_s, 4, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_55.setObjectName("label_55")
        self.gridLayout_9.addWidget(self.label_55, 3, 0, 1, 1)
        self.doubleSpinBox_first_dsh = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        self.doubleSpinBox_first_dsh.setObjectName("doubleSpinBox_first_dsh")
        self.gridLayout_9.addWidget(self.doubleSpinBox_first_dsh, 3, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_61.setObjectName("label_61")
        self.gridLayout_9.addWidget(self.label_61, 0, 0, 1, 1)
        self.doubleSpinBox_first_rho_fp = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_9)
        self.doubleSpinBox_first_rho_fp.setObjectName("doubleSpinBox_first_rho_fp")
        self.gridLayout_9.addWidget(self.doubleSpinBox_first_rho_fp, 0, 1, 1, 1)
        self.pushButton_first_check = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_first_check.setGeometry(QtCore.QRect(130, 180, 81, 23))
        self.pushButton_first_check.setObjectName("pushButton_first_check")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton.setGeometry(QtCore.QRect(300, 20, 21, 23))
        self.pushButton.setText("")
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/advancedsettings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_first_check, icon3, "")
        self.tab_second_advanced = QtWidgets.QWidget()
        self.tab_second_advanced.setObjectName("tab_second_advanced")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_second_advanced)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 30, 291, 321))
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 191, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_65 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout.addWidget(self.label_65)
        self.spinBox_second_zc = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_second_zc.setEnabled(False)
        self.spinBox_second_zc.setObjectName("spinBox_second_zc")
        self.horizontalLayout.addWidget(self.spinBox_second_zc)
        self.spinBox_second_zp = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_second_zp.setObjectName("spinBox_second_zp")
        self.horizontalLayout.addWidget(self.spinBox_second_zp)
        self.label_66 = QtWidgets.QLabel(self.groupBox_9)
        self.label_66.setGeometry(QtCore.QRect(90, 10, 54, 12))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_9)
        self.label_67.setGeometry(QtCore.QRect(150, 10, 54, 12))
        self.label_67.setObjectName("label_67")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_9)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(20, 80, 211, 171))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_74 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_74.setObjectName("label_74")
        self.gridLayout_10.addWidget(self.label_74, 7, 0, 1, 1)
        self.doubleSpinBox_second_rp = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_10)
        self.doubleSpinBox_second_rp.setObjectName("doubleSpinBox_second_rp")
        self.gridLayout_10.addWidget(self.doubleSpinBox_second_rp, 2, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_73.setObjectName("label_73")
        self.gridLayout_10.addWidget(self.label_73, 5, 0, 1, 1)
        self.doubleSpinBox_second_b = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_10)
        self.doubleSpinBox_second_b.setObjectName("doubleSpinBox_second_b")
        self.gridLayout_10.addWidget(self.doubleSpinBox_second_b, 7, 1, 1, 1)
        self.doubleSpinBox_second_k2_origin = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_10)
        self.doubleSpinBox_second_k2_origin.setObjectName("doubleSpinBox_second_k2_origin")
        self.gridLayout_10.addWidget(self.doubleSpinBox_second_k2_origin, 5, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_69.setObjectName("label_69")
        self.gridLayout_10.addWidget(self.label_69, 3, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_80.setObjectName("label_80")
        self.gridLayout_10.addWidget(self.label_80, 2, 0, 1, 1)
        self.doubleSpinBox_second_k1_origin = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_10)
        self.doubleSpinBox_second_k1_origin.setObjectName("doubleSpinBox_second_k1_origin")
        self.gridLayout_10.addWidget(self.doubleSpinBox_second_k1_origin, 3, 1, 1, 1)
        self.pushButton_second_k1_origin = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_second_k1_origin.setGeometry(QtCore.QRect(240, 130, 21, 23))
        self.pushButton_second_k1_origin.setText("")
        self.pushButton_second_k1_origin.setIcon(icon2)
        self.pushButton_second_k1_origin.setObjectName("pushButton_second_k1_origin")
        self.pushButton_second_k2_origin = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_second_k2_origin.setGeometry(QtCore.QRect(240, 170, 21, 23))
        self.pushButton_second_k2_origin.setText("")
        self.pushButton_second_k2_origin.setIcon(icon2)
        self.pushButton_second_k2_origin.setObjectName("pushButton_second_k2_origin")
        self.pushButton_second_calculate = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_second_calculate.setGeometry(QtCore.QRect(90, 270, 75, 23))
        self.pushButton_second_calculate.setObjectName("pushButton_second_calculate")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_second_advanced)
        self.groupBox_10.setGeometry(QtCore.QRect(420, 40, 311, 291))
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_10)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(40, 30, 221, 256))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_85 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_85.setObjectName("label_85")
        self.gridLayout_11.addWidget(self.label_85, 9, 0, 1, 1)
        self.lineEdit_second_rc = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_rc.setEnabled(False)
        self.lineEdit_second_rc.setObjectName("lineEdit_second_rc")
        self.gridLayout_11.addWidget(self.lineEdit_second_rc, 5, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_86.setObjectName("label_86")
        self.gridLayout_11.addWidget(self.label_86, 10, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_84.setObjectName("label_84")
        self.gridLayout_11.addWidget(self.label_84, 8, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_78.setObjectName("label_78")
        self.gridLayout_11.addWidget(self.label_78, 2, 0, 1, 1)
        self.lineEdit_second_rp_pie = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_rp_pie.setEnabled(False)
        self.lineEdit_second_rp_pie.setObjectName("lineEdit_second_rp_pie")
        self.gridLayout_11.addWidget(self.lineEdit_second_rp_pie, 2, 1, 1, 1)
        self.lineEdit_second_rc_pie = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_rc_pie.setEnabled(False)
        self.lineEdit_second_rc_pie.setObjectName("lineEdit_second_rc_pie")
        self.gridLayout_11.addWidget(self.lineEdit_second_rc_pie, 3, 1, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_79.setObjectName("label_79")
        self.gridLayout_11.addWidget(self.label_79, 3, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_71.setObjectName("label_71")
        self.gridLayout_11.addWidget(self.label_71, 0, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_81.setObjectName("label_81")
        self.gridLayout_11.addWidget(self.label_81, 5, 0, 1, 1)
        self.lineEdit_second_r_fc = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_r_fc.setEnabled(False)
        self.lineEdit_second_r_fc.setObjectName("lineEdit_second_r_fc")
        self.gridLayout_11.addWidget(self.lineEdit_second_r_fc, 9, 1, 1, 1)
        self.lineEdit_second_r_fp = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_r_fp.setEnabled(False)
        self.lineEdit_second_r_fp.setObjectName("lineEdit_second_r_fp")
        self.gridLayout_11.addWidget(self.lineEdit_second_r_fp, 7, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_82.setObjectName("label_82")
        self.gridLayout_11.addWidget(self.label_82, 6, 0, 1, 1)
        self.lineEdit_second_r_ac = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_r_ac.setEnabled(False)
        self.lineEdit_second_r_ac.setObjectName("lineEdit_second_r_ac")
        self.gridLayout_11.addWidget(self.lineEdit_second_r_ac, 8, 1, 1, 1)
        self.lineEdit_second_r_ap = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_r_ap.setEnabled(False)
        self.lineEdit_second_r_ap.setObjectName("lineEdit_second_r_ap")
        self.gridLayout_11.addWidget(self.lineEdit_second_r_ap, 6, 1, 1, 1)
        self.lineEdit_second_p_pie = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_p_pie.setEnabled(False)
        self.lineEdit_second_p_pie.setObjectName("lineEdit_second_p_pie")
        self.gridLayout_11.addWidget(self.lineEdit_second_p_pie, 10, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_68.setObjectName("label_68")
        self.gridLayout_11.addWidget(self.label_68, 1, 0, 1, 1)
        self.lineEdit_second_k2 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_k2.setEnabled(False)
        self.lineEdit_second_k2.setObjectName("lineEdit_second_k2")
        self.gridLayout_11.addWidget(self.lineEdit_second_k2, 1, 1, 1, 1)
        self.lineEdit_second_k1 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_second_k1.setEnabled(False)
        self.lineEdit_second_k1.setObjectName("lineEdit_second_k1")
        self.gridLayout_11.addWidget(self.lineEdit_second_k1, 0, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_83.setObjectName("label_83")
        self.gridLayout_11.addWidget(self.label_83, 7, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_second_advanced)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 390, 291, 131))
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_11)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(40, 20, 191, 61))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_70 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_70.setObjectName("label_70")
        self.gridLayout_12.addWidget(self.label_70, 0, 0, 1, 1)
        self.doubleSpinBox_second_a = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_12)
        self.doubleSpinBox_second_a.setEnabled(True)
        self.doubleSpinBox_second_a.setObjectName("doubleSpinBox_second_a")
        self.gridLayout_12.addWidget(self.doubleSpinBox_second_a, 0, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_75.setObjectName("label_75")
        self.gridLayout_12.addWidget(self.label_75, 1, 0, 1, 1)
        self.doubleSpinBox_second_r_rp = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_12)
        self.doubleSpinBox_second_r_rp.setObjectName("doubleSpinBox_second_r_rp")
        self.gridLayout_12.addWidget(self.doubleSpinBox_second_r_rp, 1, 1, 1, 1)
        self.pushButton_second_set = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_second_set.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.pushButton_second_set.setObjectName("pushButton_second_set")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_second_advanced)
        self.groupBox_12.setGeometry(QtCore.QRect(420, 380, 271, 171))
        self.groupBox_12.setObjectName("groupBox_12")
        self.pushButton_second_draw_cycloid_gear = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_second_draw_cycloid_gear.setGeometry(QtCore.QRect(90, 140, 81, 23))
        self.pushButton_second_draw_cycloid_gear.setObjectName("pushButton_second_draw_cycloid_gear")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_12)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(40, 20, 181, 101))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_87 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_87.setObjectName("label_87")
        self.gridLayout_13.addWidget(self.label_87, 2, 0, 1, 1)
        self.doubleSpinBox_second_delta = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_13)
        self.doubleSpinBox_second_delta.setDecimals(4)
        self.doubleSpinBox_second_delta.setMinimum(-99.0)
        self.doubleSpinBox_second_delta.setObjectName("doubleSpinBox_second_delta")
        self.gridLayout_13.addWidget(self.doubleSpinBox_second_delta, 2, 1, 1, 1)
        self.doubleSpinBox_second_delta_rp = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_13)
        self.doubleSpinBox_second_delta_rp.setMinimum(-99.0)
        self.doubleSpinBox_second_delta_rp.setObjectName("doubleSpinBox_second_delta_rp")
        self.gridLayout_13.addWidget(self.doubleSpinBox_second_delta_rp, 0, 1, 1, 1)
        self.doubleSpinBox_second_delta_r_rp = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_13)
        self.doubleSpinBox_second_delta_r_rp.setMinimum(-99.0)
        self.doubleSpinBox_second_delta_r_rp.setObjectName("doubleSpinBox_second_delta_r_rp")
        self.gridLayout_13.addWidget(self.doubleSpinBox_second_delta_r_rp, 1, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_76.setObjectName("label_76")
        self.gridLayout_13.addWidget(self.label_76, 0, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_77.setObjectName("label_77")
        self.gridLayout_13.addWidget(self.label_77, 1, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.groupBox_12)
        self.label_88.setGeometry(QtCore.QRect(230, 90, 21, 16))
        self.label_88.setObjectName("label_88")
        self.tabWidget.addTab(self.tab_second_advanced, icon1, "")
        self.tab_second_check = QtWidgets.QWidget()
        self.tab_second_check.setObjectName("tab_second_check")
        self.pushButton_second_check = QtWidgets.QPushButton(self.tab_second_check)
        self.pushButton_second_check.setGeometry(QtCore.QRect(110, 420, 81, 23))
        self.pushButton_second_check.setObjectName("pushButton_second_check")
        self.tabWidget.addTab(self.tab_second_check, icon3, "")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 600, 1031, 141))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1012, 122))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_help = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_help.setGeometry(QtCore.QRect(20, -40, 1001, 181))
        self.label_help.setText("")
        self.label_help.setPixmap(QtGui.QPixmap("labels/help_rv.jpg"))
        self.label_help.setObjectName("label_help")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1239, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu_file = QtWidgets.QMenu(self.menuBar)
        self.menu_file.setObjectName("menu_file")
        self.menu_exportReport = QtWidgets.QMenu(self.menu_file)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/fileexport.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_exportReport.setIcon(icon4)
        self.menu_exportReport.setObjectName("menu_exportReport")
        self.menu_tools = QtWidgets.QMenu(self.menuBar)
        self.menu_tools.setObjectName("menu_tools")
        self.menu_help = QtWidgets.QMenu(self.menuBar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(180, 650))
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 989, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget_module = QtWidgets.QTreeWidget(self.verticalLayoutWidget)
        self.treeWidget_module.setObjectName("treeWidget_module")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_module)
        item_0.setIcon(0, icon)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_module)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/cog_gear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon5)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/settings_setting.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon6)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_module)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/gear_wheel.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon7)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setIcon(0, icon6)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_module)
        item_0.setIcon(0, icon3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget_module)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_openfile = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_openfile.setIcon(icon8)
        self.action_openfile.setObjectName("action_openfile")
        self.action_savefile = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/Save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_savefile.setIcon(icon9)
        self.action_savefile.setObjectName("action_savefile")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_Excel = QtWidgets.QAction(MainWindow)
        self.action_Excel.setObjectName("action_Excel")
        self.action_setting = QtWidgets.QAction(MainWindow)
        self.action_setting.setIcon(icon6)
        self.action_setting.setObjectName("action_setting")
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/sign_out_exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon10)
        self.action_exit.setObjectName("action_exit")
        self.action_manual = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/manual.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_manual.setIcon(icon11)
        self.action_manual.setObjectName("action_manual")
        self.action_recommend = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/feedback.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_recommend.setIcon(icon12)
        self.action_recommend.setObjectName("action_recommend")
        self.action_about = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon13)
        self.action_about.setObjectName("action_about")
        self.action_teeth_match_tool = QtWidgets.QAction(MainWindow)
        self.action_teeth_match_tool.setObjectName("action_teeth_match_tool")
        self.action_structure_optimal = QtWidgets.QAction(MainWindow)
        self.action_structure_optimal.setObjectName("action_structure_optimal")
        self.menu_file.addAction(self.action_openfile)
        self.menu_file.addAction(self.action_savefile)
        self.menu_file.addAction(self.menu_exportReport.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_setting)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_tools.addAction(self.action_teeth_match_tool)
        self.menu_tools.addAction(self.action_structure_optimal)
        self.menu_help.addAction(self.action_manual)
        self.menu_help.addAction(self.action_recommend)
        self.menu_help.addAction(self.action_about)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_tools.menuAction())
        self.menuBar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "RV减速器设计软件", None, -1))
        self.groupBox_13.setTitle(QtWidgets.QApplication.translate("MainWindow", "1 基本参数", None, -1))
        self.label_92.setText(QtWidgets.QApplication.translate("MainWindow", "总传动比（初选）", None, -1))
        self.label_99.setText(QtWidgets.QApplication.translate("MainWindow", "一级传动比（初选）", None, -1))
        self.label_72.setText(QtWidgets.QApplication.translate("MainWindow", "渐开线中心轮齿数(初选)", None, -1))
        self.label_94.setText(QtWidgets.QApplication.translate("MainWindow", "针齿中心圆半径rp", None, -1))
        self.label_main_a0.setText(QtWidgets.QApplication.translate("MainWindow", "推荐值", None, -1))
        self.pushButton_main_a0_calc.setText(QtWidgets.QApplication.translate("MainWindow", "计算中心距范围", None, -1))
        self.pushButton_main_zp_calc.setText(QtWidgets.QApplication.translate("MainWindow", "计算针轮齿数Zp", None, -1))
        self.groupBox_14.setTitle(QtWidgets.QApplication.translate("MainWindow", "2 渐开线行星传动配齿工具", None, -1))
        self.label_101.setText(QtWidgets.QApplication.translate("MainWindow", "传动比允许误差", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "±5%", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "±10%", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "±15%", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "±20%", None, -1))
        self.label_97.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮数量", None, -1))
        self.radioButton_actual_center_distance.setText(QtWidgets.QApplication.translate("MainWindow", "中心距", None, -1))
        self.radioButton_normal_module.setText(QtWidgets.QApplication.translate("MainWindow", "法向模数", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "中心轮齿数", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "行星轮齿数", None, -1))
        self.tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "模数", None, -1))
        self.tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "中心距", None, -1))
        self.tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "传动比", None, -1))
        self.pushButton_main_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "计算方案", None, -1))
        self.label_102.setText(QtWidgets.QApplication.translate("MainWindow", "已考虑渐开线行星传动正确临接条件", None, -1))
        self.groupBox_15.setTitle(QtWidgets.QApplication.translate("MainWindow", "3 总传动比计算", None, -1))
        self.label_89.setText(QtWidgets.QApplication.translate("MainWindow", "中心轮齿数z1", None, -1))
        self.label_93.setText(QtWidgets.QApplication.translate("MainWindow", "实际总传动比", None, -1))
        self.label_90.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮齿数z2", None, -1))
        self.pushButton_main_speed_ratio_calc.setText(QtWidgets.QApplication.translate("MainWindow", "计算传动比", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main_design), QtWidgets.QApplication.translate("MainWindow", "总体设计", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "1 基本参数", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "齿根高系数hf*", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "法向模数mn", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "齿根高系数ha*", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "有效齿宽b", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "法向压力角αn", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "中心轮", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "齿数z", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "齿宽b", None, -1))
        self.pushButton_teethmatch_tool.setText(QtWidgets.QApplication.translate("MainWindow", "配齿工具", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "2 设置参数", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "啮合角α\'", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "中心距", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "总变位系数", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "中心轮变位系数", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮变位系数", None, -1))
        self.pushButton_first_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "计算参数", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "3 几何尺寸参数", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "最大滑动率", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "齿顶圆压力角", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "齿顶圆直径da", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "齿根圆直径df", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "估算结果：", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "中心轮", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "齿形重合度εα", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "齿向重合度εβ", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "4 精度等级", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "单位：μm", None, -1))
        self.comboBox_accuracy_level.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "1级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "2级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "3级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "4级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "5级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "6级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "7级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "8级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "9级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "10级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "11级 GB 10095", None, -1))
        self.comboBox_accuracy_level.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "12级 GB 10095", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "齿廓形状偏差ffα", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "齿向公差Fβ", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "工法线长度变动公差Fw", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "齿圈径向跳动公差Fr", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "单个齿距累积偏差fpt", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "齿距累积公差Fp", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "径向综合公差Fi", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "中心轮", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_first_advanced), QtWidgets.QApplication.translate("MainWindow", "一级渐开线齿轮 设计", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "强度参数", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "输入扭矩（N·m）", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "主动轮转速(r/min))", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("MainWindow", "使用系数KA", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮数量", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("MainWindow", "中心轮", None, -1))
        self.label_56.setText(QtWidgets.QApplication.translate("MainWindow", "弹性模量", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("MainWindow", "接触疲劳极限δHlim", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("MainWindow", "弯曲疲劳极限δFlim", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("MainWindow", "泊松比", None, -1))
        self.label_60.setText(QtWidgets.QApplication.translate("MainWindow", "接触强度寿命系数Znt", None, -1))
        self.label_59.setText(QtWidgets.QApplication.translate("MainWindow", "硬度(HB)", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("MainWindow", "最小安全系数SHmin", None, -1))
        self.label_62.setText(QtWidgets.QApplication.translate("MainWindow", "最小安全系数SFmin", None, -1))
        self.label_63.setText(QtWidgets.QApplication.translate("MainWindow", "弯曲强度寿命系数Ynt", None, -1))
        self.label_64.setText(QtWidgets.QApplication.translate("MainWindow", "滑移层厚度ρ\'", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "校核结果", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "接触应力δH", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "弯曲强度安全系数SF", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "接触强度安全系数SH", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "许用弯曲应力δFP", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "许用接触应力δHP", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "弯曲应力δF", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "中心轮工作强度", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "行星轮工作强度", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "其他参数", None, -1))
        self.label_50.setText(QtWidgets.QApplication.translate("MainWindow", "40°润滑油粘度", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "齿轮中点与轴承中心距离s", None, -1))
        self.label_54.setText(QtWidgets.QApplication.translate("MainWindow", "结构系数K", None, -1))
        self.label_53.setText(QtWidgets.QApplication.translate("MainWindow", "轴承跨距l", None, -1))
        self.label_55.setText(QtWidgets.QApplication.translate("MainWindow", "小轮轴当量直径dsh", None, -1))
        self.label_61.setText(QtWidgets.QApplication.translate("MainWindow", "刀具齿顶圆角Rf", None, -1))
        self.pushButton_first_check.setText(QtWidgets.QApplication.translate("MainWindow", "参数校核", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_first_check), QtWidgets.QApplication.translate("MainWindow", "一级渐开线齿轮 校核", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("MainWindow", "1 基本参数", None, -1))
        self.label_65.setText(QtWidgets.QApplication.translate("MainWindow", "齿数z", None, -1))
        self.label_66.setText(QtWidgets.QApplication.translate("MainWindow", "摆线轮", None, -1))
        self.label_67.setText(QtWidgets.QApplication.translate("MainWindow", "针轮", None, -1))
        self.label_74.setText(QtWidgets.QApplication.translate("MainWindow", "齿宽b", None, -1))
        self.label_73.setText(QtWidgets.QApplication.translate("MainWindow", "针径系数K2（初选）", None, -1))
        self.label_69.setText(QtWidgets.QApplication.translate("MainWindow", "短幅系数K1（初选）", None, -1))
        self.label_80.setText(QtWidgets.QApplication.translate("MainWindow", "针齿中心圆半径rp", None, -1))
        self.pushButton_second_calculate.setText(QtWidgets.QApplication.translate("MainWindow", "计算参数", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("MainWindow", "3 几何尺寸参数", None, -1))
        self.label_85.setText(QtWidgets.QApplication.translate("MainWindow", "摆线轮齿根圆半径r fc", None, -1))
        self.label_86.setText(QtWidgets.QApplication.translate("MainWindow", "节圆齿距p\'", None, -1))
        self.label_84.setText(QtWidgets.QApplication.translate("MainWindow", "摆线轮齿顶圆半径r ac", None, -1))
        self.label_78.setText(QtWidgets.QApplication.translate("MainWindow", "针轮节圆半径rp\'", None, -1))
        self.label_79.setText(QtWidgets.QApplication.translate("MainWindow", "摆线轮节圆半径rc\'", None, -1))
        self.label_71.setText(QtWidgets.QApplication.translate("MainWindow", "短幅系数K1", None, -1))
        self.label_81.setText(QtWidgets.QApplication.translate("MainWindow", "摆线轮基圆半径rc", None, -1))
        self.label_82.setText(QtWidgets.QApplication.translate("MainWindow", "针轮齿顶圆半径r ap", None, -1))
        self.label_68.setText(QtWidgets.QApplication.translate("MainWindow", "针径系数K2", None, -1))
        self.label_83.setText(QtWidgets.QApplication.translate("MainWindow", "针轮齿根圆半径r fp", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("MainWindow", "2 其它参数", None, -1))
        self.label_70.setText(QtWidgets.QApplication.translate("MainWindow", "偏心距a", None, -1))
        self.label_75.setText(QtWidgets.QApplication.translate("MainWindow", "针齿半径r rp", None, -1))
        self.pushButton_second_set.setText(QtWidgets.QApplication.translate("MainWindow", "设置参数", None, -1))
        self.groupBox_12.setTitle(QtWidgets.QApplication.translate("MainWindow", "4 修形摆线齿廓", None, -1))
        self.pushButton_second_draw_cycloid_gear.setText(QtWidgets.QApplication.translate("MainWindow", "绘制摆线齿廓", None, -1))
        self.label_87.setText(QtWidgets.QApplication.translate("MainWindow", "转角修形δ", None, -1))
        self.label_76.setText(QtWidgets.QApplication.translate("MainWindow", "移距修形Δrp", None, -1))
        self.label_77.setText(QtWidgets.QApplication.translate("MainWindow", "等距修形Δr rp", None, -1))
        self.label_88.setText(QtWidgets.QApplication.translate("MainWindow", "deg", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_second_advanced), QtWidgets.QApplication.translate("MainWindow", "二级摆线针轮 设计", None, -1))
        self.pushButton_second_check.setText(QtWidgets.QApplication.translate("MainWindow", "参数校核", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_second_check), QtWidgets.QApplication.translate("MainWindow", "二级摆线针轮 校核", None, -1))
        self.menu_file.setTitle(QtWidgets.QApplication.translate("MainWindow", "文件", None, -1))
        self.menu_exportReport.setTitle(QtWidgets.QApplication.translate("MainWindow", "导出参数报告", None, -1))
        self.menu_tools.setTitle(QtWidgets.QApplication.translate("MainWindow", "工具", None, -1))
        self.menu_help.setTitle(QtWidgets.QApplication.translate("MainWindow", "帮助", None, -1))
        self.dockWidget_3.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "模块", None, -1))
        self.treeWidget_module.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "功能信息", None, -1))
        __sortingEnabled = self.treeWidget_module.isSortingEnabled()
        self.treeWidget_module.setSortingEnabled(False)
        self.treeWidget_module.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "总体设计", None, -1))
        self.treeWidget_module.topLevelItem(1).setText(0, QtWidgets.QApplication.translate("MainWindow", "一级渐开线齿轮", None, -1))
        self.treeWidget_module.topLevelItem(1).child(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "一级渐开线齿轮 设计", None, -1))
        self.treeWidget_module.topLevelItem(1).child(1).setText(0, QtWidgets.QApplication.translate("MainWindow", "一级渐开线齿轮 校核", None, -1))
        self.treeWidget_module.topLevelItem(2).setText(0, QtWidgets.QApplication.translate("MainWindow", "二级摆线针轮", None, -1))
        self.treeWidget_module.topLevelItem(2).child(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "二级摆线针轮 设计", None, -1))
        self.treeWidget_module.topLevelItem(2).child(1).setText(0, QtWidgets.QApplication.translate("MainWindow", "二级摆线针轮 校核", None, -1))
        self.treeWidget_module.topLevelItem(3).setText(0, QtWidgets.QApplication.translate("MainWindow", "参数校核结果", None, -1))
        self.treeWidget_module.topLevelItem(3).child(0).setText(0, QtWidgets.QApplication.translate("MainWindow", "回差分析", None, -1))
        self.treeWidget_module.topLevelItem(3).child(1).setText(0, QtWidgets.QApplication.translate("MainWindow", "传动误差", None, -1))
        self.treeWidget_module.topLevelItem(3).child(2).setText(0, QtWidgets.QApplication.translate("MainWindow", "刚度分析", None, -1))
        self.treeWidget_module.setSortingEnabled(__sortingEnabled)
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.action_openfile.setText(QtWidgets.QApplication.translate("MainWindow", "打开参数文件", None, -1))
        self.action_openfile.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.action_savefile.setText(QtWidgets.QApplication.translate("MainWindow", "保存参数文件", None, -1))
        self.action_savefile.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.action_6.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.action_Excel.setText(QtWidgets.QApplication.translate("MainWindow", "导出Excel格式报告", None, -1))
        self.action_setting.setText(QtWidgets.QApplication.translate("MainWindow", "设置", None, -1))
        self.action_exit.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.action_manual.setText(QtWidgets.QApplication.translate("MainWindow", "使用手册", None, -1))
        self.action_manual.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F1", None, -1))
        self.action_recommend.setText(QtWidgets.QApplication.translate("MainWindow", "意见反馈", None, -1))
        self.action_about.setText(QtWidgets.QApplication.translate("MainWindow", "关于", None, -1))
        self.action_teeth_match_tool.setText(QtWidgets.QApplication.translate("MainWindow", "配齿工具", None, -1))
        self.action_structure_optimal.setText(QtWidgets.QApplication.translate("MainWindow", "结构优化", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

