# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\OneDrive\PythonFile\RV_software\RV_1213\teethmatch_tool_window.ui',
# licensing of 'F:\OneDrive\PythonFile\RV_software\RV_1213\teethmatch_tool_window.ui' applies.
#
# Created: Mon Jan  7 17:31:22 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog_teethmatch_tool(object):
    def setupUi(self, Dialog_teethmatch_tool):
        Dialog_teethmatch_tool.setObjectName("Dialog_teethmatch_tool")
        Dialog_teethmatch_tool.resize(611, 578)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/advancedsettings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_teethmatch_tool.setWindowIcon(icon)
        Dialog_teethmatch_tool.setSizeGripEnabled(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog_teethmatch_tool)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 571, 151))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 501, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_speed_ratio = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_speed_ratio.setObjectName("doubleSpinBox_speed_ratio")
        self.gridLayout.addWidget(self.doubleSpinBox_speed_ratio, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.doubleSpinBox_beta_angle = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_beta_angle.setMaximum(999999.99)
        self.doubleSpinBox_beta_angle.setObjectName("doubleSpinBox_beta_angle")
        self.gridLayout.addWidget(self.doubleSpinBox_beta_angle, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.comboBox_speed_ratio_deviation = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_speed_ratio_deviation.setObjectName("comboBox_speed_ratio_deviation")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.comboBox_speed_ratio_deviation.addItem("")
        self.gridLayout.addWidget(self.comboBox_speed_ratio_deviation, 1, 3, 1, 1)
        self.spinBox_gearteeth_min = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_gearteeth_min.setMaximum(999999)
        self.spinBox_gearteeth_min.setObjectName("spinBox_gearteeth_min")
        self.gridLayout.addWidget(self.spinBox_gearteeth_min, 0, 3, 1, 1)
        self.radioButton_actual_center_distance = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_actual_center_distance.setGeometry(QtCore.QRect(30, 120, 89, 16))
        self.radioButton_actual_center_distance.setObjectName("radioButton_actual_center_distance")
        self.radioButton_normal_module = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_normal_module.setGeometry(QtCore.QRect(180, 120, 89, 16))
        self.radioButton_normal_module.setObjectName("radioButton_normal_module")
        self.doubleSpinBox_d_or_mn = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_d_or_mn.setGeometry(QtCore.QRect(340, 120, 141, 22))
        self.doubleSpinBox_d_or_mn.setMaximum(999999.99)
        self.doubleSpinBox_d_or_mn.setObjectName("doubleSpinBox_d_or_mn")
        self.pushButton_calculate = QtWidgets.QPushButton(Dialog_teethmatch_tool)
        self.pushButton_calculate.setGeometry(QtCore.QRect(240, 180, 121, 31))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_teethmatch_tool)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 540, 211, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.tableWidget = QtWidgets.QTableWidget(Dialog_teethmatch_tool)
        self.tableWidget.setGeometry(QtCore.QRect(0, 220, 601, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Dialog_teethmatch_tool)
        QtCore.QObject.connect(self.pushButton_cancel, QtCore.SIGNAL("clicked()"), Dialog_teethmatch_tool.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog_teethmatch_tool)

    def retranslateUi(self, Dialog_teethmatch_tool):
        Dialog_teethmatch_tool.setWindowTitle(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "配齿工具", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "参数", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "最小齿数", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "速比", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "螺旋角", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "速比允许误差", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(0, QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "±5%", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(1, QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "±10%", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(2, QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "±15%", None, -1))
        self.comboBox_speed_ratio_deviation.setItemText(3, QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "±20%", None, -1))
        self.radioButton_actual_center_distance.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "中心距", None, -1))
        self.radioButton_normal_module.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "法向模数", None, -1))
        self.pushButton_calculate.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "计算方案", None, -1))
        self.pushButton_ok.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "确定", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "取消", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "中心轮齿数", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "行星轮齿数", None, -1))
        self.tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "法向模数", None, -1))
        self.tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "螺旋角", None, -1))
        self.tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "中心距", None, -1))
        self.tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Dialog_teethmatch_tool", "速比", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_teethmatch_tool = QtWidgets.QDialog()
    ui = Ui_Dialog_teethmatch_tool()
    ui.setupUi(Dialog_teethmatch_tool)
    Dialog_teethmatch_tool.show()
    sys.exit(app.exec_())

