# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\OneDrive\PythonFile\RV_software\RV_1211.5\GA\GA.ui',
# licensing of 'F:\OneDrive\PythonFile\RV_software\RV_1211.5\GA\GA.ui' applies.
#
# Created: Tue Dec 11 19:43:35 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog_GA(object):
    def setupUi(self, Dialog_GA):
        Dialog_GA.setObjectName("Dialog_GA")
        Dialog_GA.resize(950, 789)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/DNA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_GA.setWindowIcon(icon)
        Dialog_GA.setSizeGripEnabled(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog_GA)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 231, 171))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 211, 131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_P = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_P.setMaximum(10000.0)
        self.doubleSpinBox_P.setObjectName("doubleSpinBox_P")
        self.gridLayout_2.addWidget(self.doubleSpinBox_P, 0, 1, 1, 1)
        self.spinBox_n_p = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_n_p.setMinimum(2)
        self.spinBox_n_p.setMaximum(3)
        self.spinBox_n_p.setProperty("value", 3)
        self.spinBox_n_p.setObjectName("spinBox_n_p")
        self.gridLayout_2.addWidget(self.spinBox_n_p, 2, 1, 1, 1)
        self.doubleSpinBox_n = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_n.setMaximum(10000.0)
        self.doubleSpinBox_n.setObjectName("doubleSpinBox_n")
        self.gridLayout_2.addWidget(self.doubleSpinBox_n, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.doubleSpinBox_T_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_T_2.setMaximum(10000000.0)
        self.doubleSpinBox_T_2.setObjectName("doubleSpinBox_T_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_T_2, 3, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_GA)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 30, 231, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 201, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_recopt = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_recopt.setMaximum(1.0)
        self.doubleSpinBox_recopt.setSingleStep(0.1)
        self.doubleSpinBox_recopt.setProperty("value", 0.9)
        self.doubleSpinBox_recopt.setObjectName("doubleSpinBox_recopt")
        self.gridLayout.addWidget(self.doubleSpinBox_recopt, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBox_MAXGEN = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_MAXGEN.setMaximum(1000)
        self.spinBox_MAXGEN.setProperty("value", 300)
        self.spinBox_MAXGEN.setObjectName("spinBox_MAXGEN")
        self.gridLayout.addWidget(self.spinBox_MAXGEN, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinBox_NIND = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_NIND.setMaximum(100000)
        self.spinBox_NIND.setProperty("value", 8000)
        self.spinBox_NIND.setObjectName("spinBox_NIND")
        self.gridLayout.addWidget(self.spinBox_NIND, 0, 1, 1, 1)
        self.doubleSpinBox_GGAP = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GGAP.setMaximum(1.0)
        self.doubleSpinBox_GGAP.setSingleStep(0.1)
        self.doubleSpinBox_GGAP.setProperty("value", 0.5)
        self.doubleSpinBox_GGAP.setObjectName("doubleSpinBox_GGAP")
        self.gridLayout.addWidget(self.doubleSpinBox_GGAP, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.doubleSpinBox_pm = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_pm.setMaximum(1.0)
        self.doubleSpinBox_pm.setSingleStep(0.1)
        self.doubleSpinBox_pm.setProperty("value", 0.1)
        self.doubleSpinBox_pm.setObjectName("doubleSpinBox_pm")
        self.gridLayout.addWidget(self.doubleSpinBox_pm, 4, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog_GA)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 220, 231, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 201, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_q_sorted = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_q_sorted.setObjectName("radioButton_q_sorted")
        self.gridLayout_3.addWidget(self.radioButton_q_sorted, 2, 0, 1, 1)
        self.radioButton_awGA = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_awGA.setObjectName("radioButton_awGA")
        self.gridLayout_3.addWidget(self.radioButton_awGA, 1, 0, 1, 1)
        self.radioButton_rwGA = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_rwGA.setObjectName("radioButton_rwGA")
        self.gridLayout_3.addWidget(self.radioButton_rwGA, 1, 1, 1, 1)
        self.radioButton_q_sorted_new = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_q_sorted_new.setObjectName("radioButton_q_sorted_new")
        self.gridLayout_3.addWidget(self.radioButton_q_sorted_new, 2, 1, 1, 1)
        self.radioButton_NSGA_II = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_NSGA_II.setObjectName("radioButton_NSGA_II")
        self.gridLayout_3.addWidget(self.radioButton_NSGA_II, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog_GA)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 260, 271, 521))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 256, 491))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinBox_z1_max = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_z1_max.setProperty("value", 30)
        self.spinBox_z1_max.setObjectName("spinBox_z1_max")
        self.gridLayout_4.addWidget(self.spinBox_z1_max, 2, 2, 1, 1)
        self.doubleSpinBox_D_r_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_D_r_max.setProperty("value", 12.0)
        self.doubleSpinBox_D_r_max.setObjectName("doubleSpinBox_D_r_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_D_r_max, 22, 2, 1, 1)
        self.doubleSpinBox_D_r_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_D_r_min.setProperty("value", 5.0)
        self.doubleSpinBox_D_r_min.setObjectName("doubleSpinBox_D_r_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_D_r_min, 22, 1, 1, 1)
        self.spinBox_Z_min = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_Z_min.setProperty("value", 5)
        self.spinBox_Z_min.setObjectName("spinBox_Z_min")
        self.gridLayout_4.addWidget(self.spinBox_Z_min, 24, 1, 1, 1)
        self.doubleSpinBox_L_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_L_max.setProperty("value", 0.0)
        self.doubleSpinBox_L_max.setObjectName("doubleSpinBox_L_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_L_max, 26, 2, 1, 1)
        self.doubleSpinBox_D_m_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_D_m_max.setProperty("value", 60.0)
        self.doubleSpinBox_D_m_max.setObjectName("doubleSpinBox_D_m_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_D_m_max, 20, 2, 1, 1)
        self.spinBox_z_g_min = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_z_g_min.setProperty("value", 20)
        self.spinBox_z_g_min.setObjectName("spinBox_z_g_min")
        self.gridLayout_4.addWidget(self.spinBox_z_g_min, 10, 1, 1, 1)
        self.spinBox_z2_max = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_z2_max.setProperty("value", 90)
        self.spinBox_z2_max.setObjectName("spinBox_z2_max")
        self.gridLayout_4.addWidget(self.spinBox_z2_max, 4, 2, 1, 1)
        self.doubleSpinBox_B_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_B_max.setObjectName("doubleSpinBox_B_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_B_max, 16, 2, 1, 1)
        self.doubleSpinBox_b_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_b_min.setProperty("value", 8.0)
        self.doubleSpinBox_b_min.setObjectName("doubleSpinBox_b_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_b_min, 6, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 20, 0, 1, 1)
        self.spinBox_z_g_max = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_z_g_max.setMaximum(200)
        self.spinBox_z_g_max.setProperty("value", 90)
        self.spinBox_z_g_max.setObjectName("spinBox_z_g_max")
        self.gridLayout_4.addWidget(self.spinBox_z_g_max, 10, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 18, 0, 1, 1)
        self.doubleSpinBox_D_m_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_D_m_min.setProperty("value", 20.0)
        self.doubleSpinBox_D_m_min.setObjectName("doubleSpinBox_D_m_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_D_m_min, 20, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 15, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 7, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 9, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 11, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 13, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 21, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 23, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 19, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem11, 17, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 14, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 16, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 12, 0, 1, 1)
        self.spinBox_z1_min = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_z1_min.setMinimum(17)
        self.spinBox_z1_min.setProperty("value", 17)
        self.spinBox_z1_min.setObjectName("spinBox_z1_min")
        self.gridLayout_4.addWidget(self.spinBox_z1_min, 2, 1, 1, 1)
        self.doubleSpinBox_D_z_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_D_z_min.setMaximum(999.99)
        self.doubleSpinBox_D_z_min.setObjectName("doubleSpinBox_D_z_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_D_z_min, 12, 1, 1, 1)
        self.doubleSpinBox_B_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_B_min.setObjectName("doubleSpinBox_B_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_B_min, 16, 1, 1, 1)
        self.doubleSpinBox_d_z_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_d_z_min.setProperty("value", 5.0)
        self.doubleSpinBox_d_z_min.setObjectName("doubleSpinBox_d_z_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_d_z_min, 14, 1, 1, 1)
        self.doubleSpinBox_K_1_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_K_1_min.setSingleStep(0.01)
        self.doubleSpinBox_K_1_min.setProperty("value", 0.5)
        self.doubleSpinBox_K_1_min.setObjectName("doubleSpinBox_K_1_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_K_1_min, 18, 1, 1, 1)
        self.doubleSpinBox_D_z_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_D_z_max.setMaximum(999.99)
        self.doubleSpinBox_D_z_max.setObjectName("doubleSpinBox_D_z_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_D_z_max, 12, 2, 1, 1)
        self.doubleSpinBox_d_z_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_d_z_max.setProperty("value", 10.0)
        self.doubleSpinBox_d_z_max.setObjectName("doubleSpinBox_d_z_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_d_z_max, 14, 2, 1, 1)
        self.doubleSpinBox_b_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_b_max.setProperty("value", 12.0)
        self.doubleSpinBox_b_max.setObjectName("doubleSpinBox_b_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_b_max, 6, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 6, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 8, 0, 1, 1)
        self.doubleSpinBox_L_min = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_L_min.setProperty("value", 8.0)
        self.doubleSpinBox_L_min.setObjectName("doubleSpinBox_L_min")
        self.gridLayout_4.addWidget(self.doubleSpinBox_L_min, 26, 1, 1, 1)
        self.spinBox_Z_max = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_Z_max.setProperty("value", 25)
        self.spinBox_Z_max.setObjectName("spinBox_Z_max")
        self.gridLayout_4.addWidget(self.spinBox_Z_max, 24, 2, 1, 1)
        self.doubleSpinBox_K_1_max = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.doubleSpinBox_K_1_max.setProperty("value", 0.8)
        self.doubleSpinBox_K_1_max.setObjectName("doubleSpinBox_K_1_max")
        self.gridLayout_4.addWidget(self.doubleSpinBox_K_1_max, 18, 2, 1, 1)
        self.spinBox_z2_min = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_z2_min.setProperty("value", 25)
        self.spinBox_z2_min.setObjectName("spinBox_z2_min")
        self.gridLayout_4.addWidget(self.spinBox_z2_min, 4, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 24, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 26, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 22, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 10, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 25, 1, 1, 1)
        self.spinBox_m_min = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_m_min.setProperty("value", 1)
        self.spinBox_m_min.setObjectName("spinBox_m_min")
        self.gridLayout_4.addWidget(self.spinBox_m_min, 8, 1, 1, 1)
        self.spinBox_m_max = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_m_max.setProperty("value", 3)
        self.spinBox_m_max.setObjectName("spinBox_m_max")
        self.gridLayout_4.addWidget(self.spinBox_m_max, 8, 2, 1, 1)
        self.pushButton_design_range = QtWidgets.QPushButton(Dialog_GA)
        self.pushButton_design_range.setGeometry(QtCore.QRect(60, 210, 151, 31))
        self.pushButton_design_range.setObjectName("pushButton_design_range")
        self.pushButton_optimal_calc = QtWidgets.QPushButton(Dialog_GA)
        self.pushButton_optimal_calc.setGeometry(QtCore.QRect(350, 340, 101, 31))
        self.pushButton_optimal_calc.setObjectName("pushButton_optimal_calc")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_GA)
        self.tableWidget.setGeometry(QtCore.QRect(280, 430, 661, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(17)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_GA)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 750, 661, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout.addWidget(self.label_28)
        self.doubleSpinBox_eta_min = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.doubleSpinBox_eta_min.setObjectName("doubleSpinBox_eta_min")
        self.horizontalLayout.addWidget(self.doubleSpinBox_eta_min)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout.addWidget(self.label_29)
        self.doubleSpinBox_V_max = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.doubleSpinBox_V_max.setMaximum(9999999.99)
        self.doubleSpinBox_V_max.setProperty("value", 9999999.99)
        self.doubleSpinBox_V_max.setObjectName("doubleSpinBox_V_max")
        self.horizontalLayout.addWidget(self.doubleSpinBox_V_max)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout.addWidget(self.label_30)
        self.doubleSpinBox_K_pie_min = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.doubleSpinBox_K_pie_min.setMaximum(99999999999.99)
        self.doubleSpinBox_K_pie_min.setObjectName("doubleSpinBox_K_pie_min")
        self.horizontalLayout.addWidget(self.doubleSpinBox_K_pie_min)
        self.pushButton_select = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_select.setObjectName("pushButton_select")
        self.horizontalLayout.addWidget(self.pushButton_select)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog_GA)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(700, 390, 241, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_2.addWidget(self.label_27)
        self.spinBox_pareto_max = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.spinBox_pareto_max.setMaximum(9999)
        self.spinBox_pareto_max.setProperty("value", 9999)
        self.spinBox_pareto_max.setObjectName("spinBox_pareto_max")
        self.horizontalLayout_2.addWidget(self.spinBox_pareto_max)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog_GA)
        self.groupBox_5.setGeometry(QtCore.QRect(530, 20, 411, 361))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(10, 20, 391, 331))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("labels/三目标.png"))
        self.label_31.setObjectName("label_31")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog_GA)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(280, 380, 251, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_3.addWidget(self.label_26)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)

        self.retranslateUi(Dialog_GA)
        QtCore.QMetaObject.connectSlotsByName(Dialog_GA)

    def retranslateUi(self, Dialog_GA):
        Dialog_GA.setWindowTitle(QtWidgets.QApplication.translate("Dialog_GA", "一体化RV结构优化", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog_GA", "1 基本参数", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog_GA", "输入功率P(w)", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog_GA", "行星轮个数n_p", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog_GA", "输入转速n(rpm)", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog_GA", "输出扭矩T_2(N·mm)", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Dialog_GA", "3 算法参数", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog_GA", "种群规模", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog_GA", "遗传代数", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog_GA", "代沟", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog_GA", "交叉概率", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog_GA", "变异概率", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Dialog_GA", "4 算法类型", None, -1))
        self.radioButton_q_sorted.setText(QtWidgets.QApplication.translate("Dialog_GA", "q_sorted", None, -1))
        self.radioButton_awGA.setText(QtWidgets.QApplication.translate("Dialog_GA", "awGA", None, -1))
        self.radioButton_rwGA.setText(QtWidgets.QApplication.translate("Dialog_GA", "rwGA", None, -1))
        self.radioButton_q_sorted_new.setText(QtWidgets.QApplication.translate("Dialog_GA", "q_sorted_new", None, -1))
        self.radioButton_NSGA_II.setText(QtWidgets.QApplication.translate("Dialog_GA", "NSGA-II", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("Dialog_GA", "2 设计变量范围", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Dialog_GA", "转臂轴承节圆直径D_m", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Dialog_GA", "短幅系数K_1", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Dialog_GA", "上限", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog_GA", "下限", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Dialog_GA", "针齿直径d_z", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Dialog_GA", "摆线轮齿宽B", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog_GA", "变量", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Dialog_GA", "针齿中心圆直径D_z", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Dialog_GA", "行星轮齿宽b", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Dialog_GA", "渐开线齿轮模数m", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("Dialog_GA", "圆柱滚子数量Z", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("Dialog_GA", "滚子有效长度L", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Dialog_GA", "行星轮齿数z_2", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Dialog_GA", "中心轮齿数z_1", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("Dialog_GA", "圆柱滚子直径D_r", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Dialog_GA", "摆线轮齿数z_g", None, -1))
        self.pushButton_design_range.setText(QtWidgets.QApplication.translate("Dialog_GA", "初算设计变量范围", None, -1))
        self.pushButton_optimal_calc.setText(QtWidgets.QApplication.translate("Dialog_GA", "优化运算", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Dialog_GA", "行星轮齿宽", None, -1))
        self.tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Dialog_GA", "针齿中心圆直径", None, -1))
        self.tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Dialog_GA", "针齿直径", None, -1))
        self.tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Dialog_GA", "摆线轮齿宽", None, -1))
        self.tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Dialog_GA", "短幅系数", None, -1))
        self.tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Dialog_GA", "转臂轴承节圆直径", None, -1))
        self.tableWidget.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Dialog_GA", "圆柱滚子直径", None, -1))
        self.tableWidget.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("Dialog_GA", "滚子有效长度", None, -1))
        self.tableWidget.horizontalHeaderItem(8).setText(QtWidgets.QApplication.translate("Dialog_GA", "中心轮齿数", None, -1))
        self.tableWidget.horizontalHeaderItem(9).setText(QtWidgets.QApplication.translate("Dialog_GA", "行星轮齿数", None, -1))
        self.tableWidget.horizontalHeaderItem(10).setText(QtWidgets.QApplication.translate("Dialog_GA", "渐开线齿轮模数", None, -1))
        self.tableWidget.horizontalHeaderItem(11).setText(QtWidgets.QApplication.translate("Dialog_GA", "摆线轮齿数", None, -1))
        self.tableWidget.horizontalHeaderItem(12).setText(QtWidgets.QApplication.translate("Dialog_GA", "圆柱滚子数量", None, -1))
        self.tableWidget.horizontalHeaderItem(13).setText(QtWidgets.QApplication.translate("Dialog_GA", "传动效率(%)", None, -1))
        self.tableWidget.horizontalHeaderItem(14).setText(QtWidgets.QApplication.translate("Dialog_GA", "体积(mm^3)", None, -1))
        self.tableWidget.horizontalHeaderItem(15).setText(QtWidgets.QApplication.translate("Dialog_GA", "扭转刚度(N·mm/rad)", None, -1))
        self.tableWidget.horizontalHeaderItem(16).setText(QtWidgets.QApplication.translate("Dialog_GA", "传动比", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("Dialog_GA", "传动效率下限", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("Dialog_GA", "体积上限", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("Dialog_GA", "扭转刚度下限", None, -1))
        self.pushButton_select.setText(QtWidgets.QApplication.translate("Dialog_GA", "筛选", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("Dialog_GA", "Pareto最优解上限", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("Dialog_GA", "5 Pareto前端", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("Dialog_GA", "进度", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_GA = QtWidgets.QDialog()
    ui = Ui_Dialog_GA()
    ui.setupUi(Dialog_GA)
    Dialog_GA.show()
    sys.exit(app.exec_())

